# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desciption',
            new_name='description',
        ),
    ]
